AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters: 
  NotificationEmail:
    Type: String
Resources:
  CheckAndSendInvoices:
    Type: AWS::Serverless::Function
    Properties:
      Handler: CheckAndSendInvoices.lambdaHandler
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Events:
        CheckInvoicesScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(12 hours)

  PaddleInvoiceTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "contract_start_date"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      GlobalSecondaryIndexes: 
        - IndexName: "ContractStartDate"
          KeySchema: 
            - AttributeName: "contract_start_date"
              KeyType: "HASH"
          ProvisionedThroughput: 
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
          Projection: 
            ProjectionType: "ALL"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "paddle_invoices_to_send"

  InvoiceAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Protocol: email
        Endpoint: !Ref NotificationEmail

  InvoiceAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref InvoiceAlarmTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref CheckAndSendInvoices
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: '1'